### ISSUE TITLE
About setup.md

### ISSUE THREAD

**Issue by JsHuang** [0vercl0k/pwn2own2023-miami#1]
Hi, the [uagateway-win32-x86-vs2008sp1-v1.5.12-482.zip](https://www.unified-automation.com/fileadmin/files/server/uagateway-win32-x86-vs2008sp1-v1.5.12-482.zip) could not download.
Can you add a copy of this version in the repo?
Thanks

**Comment by 0vercl0k** [comment]
I haven't added it because I am not sure about the legality around distributing it unfortunately. If you know more I'd love to hear about it.

Cheers
